### PR TITLE
add `.nvmrc` file, `@types/lodash` and `@types/uuid` has been moved to devDeps from Deps and installed `ts-reset`

### PR DESCRIPTION
**Pull request by INeedJobToStartWork**
Check Commits:

[⚙️ Chore(.nvmrc): add .nvmrc file with 20.X versions](https://github.com/webdevcody/next-drizzle-lucia-sqlite-template/commit/b40877fc30fadb25f89f505fc88ee2327e0cfe96)
[⚙️ Chore(enviroment): @types/lodash and @types/uuid moved to devDependencies and installed `ts-reset`](https://github.com/webdevcody/next-drizzle-lucia-sqlite-template/commit/ce1aa508ba53ec3aa8c05c128f478a4c63b6f685) 

# Important

added `.vscode/settings.json` by misstake and didnt mention it in commits.

### CODE REVIEW

**Comment by delasy** [comment]
you should probably move pnpm-lock.yaml to ignore

**Comment by webdevcody** [comment]
I don't think you need to commit your .vscode or .pnpm lock

**Comment by INeedJobToStartWork** [comment]
Missclick 🙈

**Comment by webdevcody** [comment]
still need pnpm lock removed, this setup assumes npm

**Comment by delasy** [comment]
Dev dependencies `@types/lodash`, `@types/uuid` are not used.

I believe this project could run on node 18, can you re-test again to see if it work on node 18?
Also, I checked most popular nextjs templates: https://github.com/topics/nextjs-template none of them have `.nvmrc` file which leads me to believe this is something that is not usually committed.

**Comment by INeedJobToStartWork** [comment]
> Also, I checked most popular nextjs templates: https://github.com/topics/nextjs-template none of them have `.nvmrc` file which leads me to believe this is something that is not usually committed.

`.nvmrc` helps ppls with _**Node Version Manager**_ to automatic change version of node in project.

[NextUI](https://github.com/nextui-org/nextui) this for example (It doesnt matter which type of project it is, it's just useful)

> I believe this project could run on node 18, can you re-test again to see if it work on node 18?

I just setup version to same as in `package.json`
```
"node": ">=20.0.0 <21.0.0"
```
I tried 18 and prob he stand up, but im getting error cuz i didnt full setup it (no db etc), just try it on your own.

**Comment by shakedhagag** [comment]
This project works well on Node 18 as well.
@INeedJobToStartWork nvm is old news my man but I guess many people still use it. I prefer fnm, look for it its awesome.

**Pull request merged**
